name = "petclub-tool"
pages_build_output_dir = "."
compatibility_date = "2026-07-09"

[[d1_databases]]
binding = "DB"
database_name = "petclub-tool-db"
database_id = "28611db4-850a-4247-afa8-cf252da64410"
